# netlify.toml

[build]
  command   = "ng build --configuration production"
  publish   = "dist/spa-webview"
  # You can remove or leave functions if you have no Netlify Functions:
  # functions = "netlify/functions"

# Disable the Angular SSR plugin entirely
[[plugins]]
  package = "@netlify/angular-runtime"
  enabled = false

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
